services:
  db:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    profiles:
      - dev
      - prod
  app:
    build:
      context: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - prod
