CREATE TABLE IF NOT EXISTS RUNNERS (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(80) NOT NULL,
    date TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USERS (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(80) NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);